-- NetSuite Financial Reporting Integration
-- Snowflake environment setup.

CREATE DATABASE IF NOT EXISTS NETSUITE_FINANCE_DEMO;
USE DATABASE NETSUITE_FINANCE_DEMO;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CONFORMED;
CREATE SCHEMA IF NOT EXISTS REPORTING;
CREATE SCHEMA IF NOT EXISTS CONTROL;

CREATE TABLE IF NOT EXISTS CONTROL.LOAD_CONTROL (
    PIPELINE_NAME           VARCHAR NOT NULL,
    RUN_ID                  VARCHAR NOT NULL,
    STARTED_AT              TIMESTAMP_NTZ NOT NULL,
    COMPLETED_AT            TIMESTAMP_NTZ,
    WATERMARK_FROM          TIMESTAMP_NTZ,
    WATERMARK_TO            TIMESTAMP_NTZ,
    SOURCE_ROW_COUNT        NUMBER,
    TARGET_ROW_COUNT        NUMBER,
    STATUS                  VARCHAR,
    ERROR_MESSAGE           VARCHAR,
    PRIMARY KEY (PIPELINE_NAME, RUN_ID)
);

CREATE TABLE IF NOT EXISTS CONTROL.RECON_EXCEPTION (
    RUN_ID                  VARCHAR NOT NULL,
    CHECK_NAME              VARCHAR NOT NULL,
    ENTITY_TYPE             VARCHAR,
    ENTITY_KEY              VARCHAR,
    EXPECTED_VALUE          NUMBER(38, 6),
    ACTUAL_VALUE            NUMBER(38, 6),
    DIFFERENCE_VALUE        NUMBER(38, 6),
    DETAILS                 VARIANT,
    DETECTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
