USE DATABASE NETSUITE_FINANCE_DEMO;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_ID              NUMBER,
    ACCOUNT_NUMBER          VARCHAR,
    ACCOUNT_NAME            VARCHAR,
    ACCOUNT_TYPE            VARCHAR,
    IS_INACTIVE             BOOLEAN,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SUBSIDIARY (
    SUBSIDIARY_ID           NUMBER,
    SUBSIDIARY_NAME         VARCHAR,
    BASE_CURRENCY_ID        NUMBER,
    IS_INACTIVE             BOOLEAN,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    DEPARTMENT_ID           NUMBER,
    DEPARTMENT_NAME         VARCHAR,
    IS_INACTIVE             BOOLEAN,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CLASS (
    CLASS_ID                NUMBER,
    CLASS_NAME              VARCHAR,
    IS_INACTIVE             BOOLEAN,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACCOUNTING_PERIOD (
    ACCOUNTING_PERIOD_ID    NUMBER,
    PERIOD_NAME             VARCHAR,
    START_DATE              DATE,
    END_DATE                DATE,
    IS_CLOSED               BOOLEAN,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURRENCY (
    CURRENCY_ID             NUMBER,
    CURRENCY_CODE           VARCHAR,
    CURRENCY_NAME           VARCHAR,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TRANSACTION_HEADER (
    TRANSACTION_ID          NUMBER,
    TRANSACTION_NUMBER      VARCHAR,
    TRANSACTION_TYPE        VARCHAR,
    TRANSACTION_DATE        DATE,
    POSTING_PERIOD_ID       NUMBER,
    SUBSIDIARY_ID           NUMBER,
    CURRENCY_ID             NUMBER,
    EXCHANGE_RATE           NUMBER(18, 8),
    POSTING_FLAG            BOOLEAN,
    MEMO                    VARCHAR,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TRANSACTION_LINE (
    TRANSACTION_ID          NUMBER,
    LINE_ID                 NUMBER,
    ACCOUNT_ID              NUMBER,
    SUBSIDIARY_ID           NUMBER,
    DEPARTMENT_ID           NUMBER,
    CLASS_ID                NUMBER,
    CURRENCY_ID             NUMBER,
    DEBIT_AMOUNT            NUMBER(18, 2),
    CREDIT_AMOUNT           NUMBER(18, 2),
    FOREIGN_AMOUNT          NUMBER(18, 2),
    LINE_MEMO               VARCHAR,
    LAST_MODIFIED_AT        TIMESTAMP_NTZ,
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
