USE DATABASE NETSUITE_FINANCE_DEMO;
USE SCHEMA CONFORMED;

CREATE OR REPLACE TABLE DIM_ACCOUNT AS
SELECT
    ACCOUNT_ID,
    ACCOUNT_NUMBER,
    ACCOUNT_NAME,
    ACCOUNT_TYPE,
    IS_INACTIVE,
    LAST_MODIFIED_AT
FROM RAW.ACCOUNT
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ACCOUNT_ID
    ORDER BY LAST_MODIFIED_AT DESC, INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE DIM_SUBSIDIARY AS
SELECT
    SUBSIDIARY_ID,
    SUBSIDIARY_NAME,
    BASE_CURRENCY_ID,
    IS_INACTIVE,
    LAST_MODIFIED_AT
FROM RAW.SUBSIDIARY
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SUBSIDIARY_ID
    ORDER BY LAST_MODIFIED_AT DESC, INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE DIM_DEPARTMENT AS
SELECT
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    IS_INACTIVE,
    LAST_MODIFIED_AT
FROM RAW.DEPARTMENT
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY DEPARTMENT_ID
    ORDER BY LAST_MODIFIED_AT DESC, INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE DIM_CLASS AS
SELECT
    CLASS_ID,
    CLASS_NAME,
    IS_INACTIVE,
    LAST_MODIFIED_AT
FROM RAW.CLASS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CLASS_ID
    ORDER BY LAST_MODIFIED_AT DESC, INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE DIM_ACCOUNTING_PERIOD AS
SELECT
    ACCOUNTING_PERIOD_ID,
    PERIOD_NAME,
    START_DATE,
    END_DATE,
    IS_CLOSED,
    LAST_MODIFIED_AT
FROM RAW.ACCOUNTING_PERIOD
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ACCOUNTING_PERIOD_ID
    ORDER BY LAST_MODIFIED_AT DESC, INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE DIM_CURRENCY AS
SELECT
    CURRENCY_ID,
    CURRENCY_CODE,
    CURRENCY_NAME,
    LAST_MODIFIED_AT
FROM RAW.CURRENCY
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CURRENCY_ID
    ORDER BY LAST_MODIFIED_AT DESC, INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE FACT_GL_LINE AS
SELECT
    L.TRANSACTION_ID,
    L.LINE_ID,
    H.TRANSACTION_NUMBER,
    H.TRANSACTION_TYPE,
    H.TRANSACTION_DATE,
    H.POSTING_PERIOD_ID,
    COALESCE(L.SUBSIDIARY_ID, H.SUBSIDIARY_ID) AS SUBSIDIARY_ID,
    L.ACCOUNT_ID,
    L.DEPARTMENT_ID,
    L.CLASS_ID,
    COALESCE(L.CURRENCY_ID, H.CURRENCY_ID) AS CURRENCY_ID,
    H.EXCHANGE_RATE,
    H.POSTING_FLAG,
    COALESCE(L.DEBIT_AMOUNT, 0) AS DEBIT_AMOUNT,
    COALESCE(L.CREDIT_AMOUNT, 0) AS CREDIT_AMOUNT,
    COALESCE(L.DEBIT_AMOUNT, 0) - COALESCE(L.CREDIT_AMOUNT, 0) AS SIGNED_AMOUNT,
    L.FOREIGN_AMOUNT,
    H.MEMO AS TRANSACTION_MEMO,
    L.LINE_MEMO,
    GREATEST(H.LAST_MODIFIED_AT, L.LAST_MODIFIED_AT) AS LAST_MODIFIED_AT
FROM RAW.TRANSACTION_HEADER H
JOIN RAW.TRANSACTION_LINE L
  ON H.TRANSACTION_ID = L.TRANSACTION_ID
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY L.TRANSACTION_ID, L.LINE_ID
    ORDER BY GREATEST(H.LAST_MODIFIED_AT, L.LAST_MODIFIED_AT) DESC,
             H.INGESTED_AT DESC,
             L.INGESTED_AT DESC
) = 1;
