USE DATABASE NETSUITE_FINANCE_DEMO;

-- Example incremental MERGE for a transaction-line fact model.
-- :WATERMARK_FROM and :WATERMARK_TO are supplied by the orchestration layer.

CREATE OR REPLACE TEMP TABLE STG_GL_LINE_INCREMENT AS
SELECT
    L.TRANSACTION_ID,
    L.LINE_ID,
    H.TRANSACTION_NUMBER,
    H.TRANSACTION_TYPE,
    H.TRANSACTION_DATE,
    H.POSTING_PERIOD_ID,
    COALESCE(L.SUBSIDIARY_ID, H.SUBSIDIARY_ID) AS SUBSIDIARY_ID,
    L.ACCOUNT_ID,
    L.DEPARTMENT_ID,
    L.CLASS_ID,
    COALESCE(L.CURRENCY_ID, H.CURRENCY_ID) AS CURRENCY_ID,
    H.EXCHANGE_RATE,
    H.POSTING_FLAG,
    COALESCE(L.DEBIT_AMOUNT, 0) AS DEBIT_AMOUNT,
    COALESCE(L.CREDIT_AMOUNT, 0) AS CREDIT_AMOUNT,
    COALESCE(L.DEBIT_AMOUNT, 0) - COALESCE(L.CREDIT_AMOUNT, 0) AS SIGNED_AMOUNT,
    L.FOREIGN_AMOUNT,
    H.MEMO AS TRANSACTION_MEMO,
    L.LINE_MEMO,
    GREATEST(H.LAST_MODIFIED_AT, L.LAST_MODIFIED_AT) AS LAST_MODIFIED_AT
FROM RAW.TRANSACTION_HEADER H
JOIN RAW.TRANSACTION_LINE L
  ON H.TRANSACTION_ID = L.TRANSACTION_ID
WHERE GREATEST(H.LAST_MODIFIED_AT, L.LAST_MODIFIED_AT) > :WATERMARK_FROM
  AND GREATEST(H.LAST_MODIFIED_AT, L.LAST_MODIFIED_AT) <= :WATERMARK_TO
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY L.TRANSACTION_ID, L.LINE_ID
    ORDER BY GREATEST(H.LAST_MODIFIED_AT, L.LAST_MODIFIED_AT) DESC,
             H.INGESTED_AT DESC,
             L.INGESTED_AT DESC
) = 1;

MERGE INTO CONFORMED.FACT_GL_LINE T
USING STG_GL_LINE_INCREMENT S
ON T.TRANSACTION_ID = S.TRANSACTION_ID
AND T.LINE_ID = S.LINE_ID
WHEN MATCHED AND S.LAST_MODIFIED_AT >= T.LAST_MODIFIED_AT THEN UPDATE SET
    TRANSACTION_NUMBER = S.TRANSACTION_NUMBER,
    TRANSACTION_TYPE = S.TRANSACTION_TYPE,
    TRANSACTION_DATE = S.TRANSACTION_DATE,
    POSTING_PERIOD_ID = S.POSTING_PERIOD_ID,
    SUBSIDIARY_ID = S.SUBSIDIARY_ID,
    ACCOUNT_ID = S.ACCOUNT_ID,
    DEPARTMENT_ID = S.DEPARTMENT_ID,
    CLASS_ID = S.CLASS_ID,
    CURRENCY_ID = S.CURRENCY_ID,
    EXCHANGE_RATE = S.EXCHANGE_RATE,
    POSTING_FLAG = S.POSTING_FLAG,
    DEBIT_AMOUNT = S.DEBIT_AMOUNT,
    CREDIT_AMOUNT = S.CREDIT_AMOUNT,
    SIGNED_AMOUNT = S.SIGNED_AMOUNT,
    FOREIGN_AMOUNT = S.FOREIGN_AMOUNT,
    TRANSACTION_MEMO = S.TRANSACTION_MEMO,
    LINE_MEMO = S.LINE_MEMO,
    LAST_MODIFIED_AT = S.LAST_MODIFIED_AT
WHEN NOT MATCHED THEN INSERT (
    TRANSACTION_ID, LINE_ID, TRANSACTION_NUMBER, TRANSACTION_TYPE,
    TRANSACTION_DATE, POSTING_PERIOD_ID, SUBSIDIARY_ID, ACCOUNT_ID,
    DEPARTMENT_ID, CLASS_ID, CURRENCY_ID, EXCHANGE_RATE, POSTING_FLAG,
    DEBIT_AMOUNT, CREDIT_AMOUNT, SIGNED_AMOUNT, FOREIGN_AMOUNT,
    TRANSACTION_MEMO, LINE_MEMO, LAST_MODIFIED_AT
) VALUES (
    S.TRANSACTION_ID, S.LINE_ID, S.TRANSACTION_NUMBER, S.TRANSACTION_TYPE,
    S.TRANSACTION_DATE, S.POSTING_PERIOD_ID, S.SUBSIDIARY_ID, S.ACCOUNT_ID,
    S.DEPARTMENT_ID, S.CLASS_ID, S.CURRENCY_ID, S.EXCHANGE_RATE, S.POSTING_FLAG,
    S.DEBIT_AMOUNT, S.CREDIT_AMOUNT, S.SIGNED_AMOUNT, S.FOREIGN_AMOUNT,
    S.TRANSACTION_MEMO, S.LINE_MEMO, S.LAST_MODIFIED_AT
);
