USE DATABASE NETSUITE_FINANCE_DEMO;
USE SCHEMA REPORTING;

CREATE OR REPLACE VIEW V_INCOME_STATEMENT AS
SELECT
    P.PERIOD_NAME,
    F.POSTING_PERIOD_ID,
    S.SUBSIDIARY_NAME,
    A.ACCOUNT_NUMBER,
    A.ACCOUNT_NAME,
    A.ACCOUNT_TYPE,
    D.DEPARTMENT_NAME,
    C.CLASS_NAME,
    SUM(F.DEBIT_AMOUNT) AS TOTAL_DEBIT,
    SUM(F.CREDIT_AMOUNT) AS TOTAL_CREDIT,
    SUM(F.SIGNED_AMOUNT) AS NET_AMOUNT
FROM CONFORMED.FACT_GL_LINE F
JOIN CONFORMED.DIM_ACCOUNT A
  ON F.ACCOUNT_ID = A.ACCOUNT_ID
JOIN CONFORMED.DIM_ACCOUNTING_PERIOD P
  ON F.POSTING_PERIOD_ID = P.ACCOUNTING_PERIOD_ID
JOIN CONFORMED.DIM_SUBSIDIARY S
  ON F.SUBSIDIARY_ID = S.SUBSIDIARY_ID
LEFT JOIN CONFORMED.DIM_DEPARTMENT D
  ON F.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN CONFORMED.DIM_CLASS C
  ON F.CLASS_ID = C.CLASS_ID
WHERE F.POSTING_FLAG = TRUE
  AND A.ACCOUNT_TYPE IN ('INCOME', 'OTHER_INCOME', 'EXPENSE', 'OTHER_EXPENSE', 'COGS')
GROUP BY ALL;

CREATE OR REPLACE VIEW V_BALANCE_SHEET AS
SELECT
    P.PERIOD_NAME,
    F.POSTING_PERIOD_ID,
    S.SUBSIDIARY_NAME,
    A.ACCOUNT_NUMBER,
    A.ACCOUNT_NAME,
    A.ACCOUNT_TYPE,
    SUM(F.DEBIT_AMOUNT) AS TOTAL_DEBIT,
    SUM(F.CREDIT_AMOUNT) AS TOTAL_CREDIT,
    SUM(F.SIGNED_AMOUNT) AS ENDING_BALANCE
FROM CONFORMED.FACT_GL_LINE F
JOIN CONFORMED.DIM_ACCOUNT A
  ON F.ACCOUNT_ID = A.ACCOUNT_ID
JOIN CONFORMED.DIM_ACCOUNTING_PERIOD P
  ON F.POSTING_PERIOD_ID = P.ACCOUNTING_PERIOD_ID
JOIN CONFORMED.DIM_SUBSIDIARY S
  ON F.SUBSIDIARY_ID = S.SUBSIDIARY_ID
WHERE F.POSTING_FLAG = TRUE
  AND A.ACCOUNT_TYPE IN ('ASSET', 'LIABILITY', 'EQUITY', 'BANK', 'ACCOUNTS_RECEIVABLE', 'ACCOUNTS_PAYABLE')
GROUP BY ALL;
