USE DATABASE NETSUITE_FINANCE_DEMO;

-- 1) Source / conformed record-count comparison
SELECT
    (SELECT COUNT(*) FROM RAW.TRANSACTION_LINE) AS RAW_LINE_COUNT,
    (SELECT COUNT(*) FROM CONFORMED.FACT_GL_LINE) AS FACT_LINE_COUNT,
    RAW_LINE_COUNT - FACT_LINE_COUNT AS DIFFERENCE;

-- 2) Duplicate transaction-line business keys
SELECT
    TRANSACTION_ID,
    LINE_ID,
    COUNT(*) AS ROW_COUNT
FROM CONFORMED.FACT_GL_LINE
GROUP BY TRANSACTION_ID, LINE_ID
HAVING COUNT(*) > 1;

-- 3) Journal debit / credit balance check
SELECT
    TRANSACTION_ID,
    SUM(DEBIT_AMOUNT) AS TOTAL_DEBIT,
    SUM(CREDIT_AMOUNT) AS TOTAL_CREDIT,
    SUM(DEBIT_AMOUNT) - SUM(CREDIT_AMOUNT) AS DIFFERENCE
FROM CONFORMED.FACT_GL_LINE
WHERE TRANSACTION_TYPE = 'JOURNAL'
  AND POSTING_FLAG = TRUE
GROUP BY TRANSACTION_ID
HAVING ABS(SUM(DEBIT_AMOUNT) - SUM(CREDIT_AMOUNT)) > 0.01;

-- 4) Posting date must fall inside accounting-period bounds
SELECT
    F.TRANSACTION_ID,
    F.TRANSACTION_DATE,
    F.POSTING_PERIOD_ID,
    P.START_DATE,
    P.END_DATE
FROM CONFORMED.FACT_GL_LINE F
JOIN CONFORMED.DIM_ACCOUNTING_PERIOD P
  ON F.POSTING_PERIOD_ID = P.ACCOUNTING_PERIOD_ID
WHERE F.TRANSACTION_DATE NOT BETWEEN P.START_DATE AND P.END_DATE;

-- 5) Account/subsidiary balance reconciliation at reporting grain
SELECT
    POSTING_PERIOD_ID,
    SUBSIDIARY_ID,
    ACCOUNT_ID,
    SUM(DEBIT_AMOUNT) AS TOTAL_DEBIT,
    SUM(CREDIT_AMOUNT) AS TOTAL_CREDIT,
    SUM(SIGNED_AMOUNT) AS NET_BALANCE
FROM CONFORMED.FACT_GL_LINE
WHERE POSTING_FLAG = TRUE
GROUP BY POSTING_PERIOD_ID, SUBSIDIARY_ID, ACCOUNT_ID;

-- 6) Missing dimension references
SELECT 'ACCOUNT' AS DIMENSION, F.ACCOUNT_ID::VARCHAR AS KEY_VALUE, COUNT(*) AS AFFECTED_ROWS
FROM CONFORMED.FACT_GL_LINE F
LEFT JOIN CONFORMED.DIM_ACCOUNT A ON F.ACCOUNT_ID = A.ACCOUNT_ID
WHERE A.ACCOUNT_ID IS NULL
GROUP BY F.ACCOUNT_ID
UNION ALL
SELECT 'SUBSIDIARY', F.SUBSIDIARY_ID::VARCHAR, COUNT(*)
FROM CONFORMED.FACT_GL_LINE F
LEFT JOIN CONFORMED.DIM_SUBSIDIARY S ON F.SUBSIDIARY_ID = S.SUBSIDIARY_ID
WHERE S.SUBSIDIARY_ID IS NULL
GROUP BY F.SUBSIDIARY_ID;

-- 7) Inactive dimensions used by posted transactions
SELECT
    F.ACCOUNT_ID,
    A.ACCOUNT_NAME,
    COUNT(*) AS POSTED_LINE_COUNT
FROM CONFORMED.FACT_GL_LINE F
JOIN CONFORMED.DIM_ACCOUNT A ON F.ACCOUNT_ID = A.ACCOUNT_ID
WHERE F.POSTING_FLAG = TRUE
  AND A.IS_INACTIVE = TRUE
GROUP BY F.ACCOUNT_ID, A.ACCOUNT_NAME;

-- 8) Currency mismatch against subsidiary base currency
SELECT
    F.TRANSACTION_ID,
    F.LINE_ID,
    F.SUBSIDIARY_ID,
    F.CURRENCY_ID AS TRANSACTION_CURRENCY_ID,
    S.BASE_CURRENCY_ID
FROM CONFORMED.FACT_GL_LINE F
JOIN CONFORMED.DIM_SUBSIDIARY S
  ON F.SUBSIDIARY_ID = S.SUBSIDIARY_ID
WHERE F.CURRENCY_ID <> S.BASE_CURRENCY_ID
  AND COALESCE(F.EXCHANGE_RATE, 0) <= 0;
