USE DATABASE NETSUITE_FINANCE_DEMO;

-- RCA 1: Detect join multiplication caused by non-unique dimension keys.
WITH BASE AS (
    SELECT TRANSACTION_ID, LINE_ID
    FROM CONFORMED.FACT_GL_LINE
),
ENRICHED AS (
    SELECT F.TRANSACTION_ID, F.LINE_ID
    FROM CONFORMED.FACT_GL_LINE F
    LEFT JOIN RAW.ACCOUNT A ON F.ACCOUNT_ID = A.ACCOUNT_ID
)
SELECT
    (SELECT COUNT(*) FROM BASE) AS BASE_ROWS,
    (SELECT COUNT(*) FROM ENRICHED) AS ENRICHED_ROWS,
    ENRICHED_ROWS - BASE_ROWS AS ROW_MULTIPLICATION;

-- RCA 2: Find duplicate raw transaction-line keys and latest versions.
SELECT
    TRANSACTION_ID,
    LINE_ID,
    COUNT(*) AS DUPLICATE_COUNT,
    MIN(LAST_MODIFIED_AT) AS FIRST_VERSION,
    MAX(LAST_MODIFIED_AT) AS LATEST_VERSION
FROM RAW.TRANSACTION_LINE
GROUP BY TRANSACTION_ID, LINE_ID
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC;

-- RCA 3: Missing / orphaned foreign keys.
SELECT
    L.TRANSACTION_ID,
    L.LINE_ID,
    L.ACCOUNT_ID,
    L.SUBSIDIARY_ID,
    L.DEPARTMENT_ID,
    L.CLASS_ID
FROM RAW.TRANSACTION_LINE L
LEFT JOIN RAW.ACCOUNT A ON L.ACCOUNT_ID = A.ACCOUNT_ID
LEFT JOIN RAW.SUBSIDIARY S ON L.SUBSIDIARY_ID = S.SUBSIDIARY_ID
LEFT JOIN RAW.DEPARTMENT D ON L.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN RAW.CLASS C ON L.CLASS_ID = C.CLASS_ID
WHERE A.ACCOUNT_ID IS NULL
   OR S.SUBSIDIARY_ID IS NULL
   OR (L.DEPARTMENT_ID IS NOT NULL AND D.DEPARTMENT_ID IS NULL)
   OR (L.CLASS_ID IS NOT NULL AND C.CLASS_ID IS NULL);

-- RCA 4: Posting-period mismatch.
SELECT
    H.TRANSACTION_ID,
    H.TRANSACTION_DATE,
    H.POSTING_PERIOD_ID,
    P.START_DATE,
    P.END_DATE,
    DATEDIFF('day', P.END_DATE, H.TRANSACTION_DATE) AS DAYS_OUTSIDE_PERIOD
FROM RAW.TRANSACTION_HEADER H
JOIN RAW.ACCOUNTING_PERIOD P
  ON H.POSTING_PERIOD_ID = P.ACCOUNTING_PERIOD_ID
WHERE H.TRANSACTION_DATE NOT BETWEEN P.START_DATE AND P.END_DATE;

-- RCA 5: Journal imbalance by transaction.
SELECT
    TRANSACTION_ID,
    SUM(DEBIT_AMOUNT) AS DEBIT_TOTAL,
    SUM(CREDIT_AMOUNT) AS CREDIT_TOTAL,
    ROUND(SUM(DEBIT_AMOUNT) - SUM(CREDIT_AMOUNT), 2) AS DIFFERENCE
FROM CONFORMED.FACT_GL_LINE
WHERE TRANSACTION_TYPE = 'JOURNAL'
GROUP BY TRANSACTION_ID
HAVING ABS(SUM(DEBIT_AMOUNT) - SUM(CREDIT_AMOUNT)) > 0.01;

-- RCA 6: Late-arriving changes after a completed run watermark.
SELECT
    F.TRANSACTION_ID,
    F.LINE_ID,
    F.LAST_MODIFIED_AT,
    C.WATERMARK_TO
FROM CONFORMED.FACT_GL_LINE F
JOIN CONTROL.LOAD_CONTROL C
  ON C.PIPELINE_NAME = 'FACT_GL_LINE'
 AND C.STATUS = 'SUCCESS'
WHERE F.LAST_MODIFIED_AT > C.WATERMARK_TO
QUALIFY ROW_NUMBER() OVER (ORDER BY C.COMPLETED_AT DESC) = 1;

-- RCA 7: Recent failed pipeline executions.
SELECT
    PIPELINE_NAME,
    RUN_ID,
    STARTED_AT,
    COMPLETED_AT,
    SOURCE_ROW_COUNT,
    TARGET_ROW_COUNT,
    ERROR_MESSAGE
FROM CONTROL.LOAD_CONTROL
WHERE STATUS = 'FAILED'
ORDER BY STARTED_AT DESC;
