USE DATABASE NETSUITE_FINANCE_DEMO;

-- Example: persist reconciliation failures for investigation.
-- Replace :RUN_ID with the orchestration run identifier.

-- Duplicate transaction-line keys.
INSERT INTO CONTROL.RECON_EXCEPTION (
    RUN_ID, CHECK_NAME, ENTITY_TYPE, ENTITY_KEY,
    EXPECTED_VALUE, ACTUAL_VALUE, DIFFERENCE_VALUE, DETAILS
)
SELECT
    :RUN_ID,
    'DUPLICATE_TRANSACTION_LINE',
    'TRANSACTION_LINE',
    TRANSACTION_ID || ':' || LINE_ID,
    1,
    COUNT(*),
    COUNT(*) - 1,
    OBJECT_CONSTRUCT('transaction_id', TRANSACTION_ID, 'line_id', LINE_ID)
FROM RAW.TRANSACTION_LINE
GROUP BY TRANSACTION_ID, LINE_ID
HAVING COUNT(*) > 1;

-- Unbalanced journal entries.
INSERT INTO CONTROL.RECON_EXCEPTION (
    RUN_ID, CHECK_NAME, ENTITY_TYPE, ENTITY_KEY,
    EXPECTED_VALUE, ACTUAL_VALUE, DIFFERENCE_VALUE, DETAILS
)
SELECT
    :RUN_ID,
    'JOURNAL_BALANCE',
    'TRANSACTION',
    TRANSACTION_ID::VARCHAR,
    0,
    SUM(DEBIT_AMOUNT) - SUM(CREDIT_AMOUNT),
    SUM(DEBIT_AMOUNT) - SUM(CREDIT_AMOUNT),
    OBJECT_CONSTRUCT(
        'total_debit', SUM(DEBIT_AMOUNT),
        'total_credit', SUM(CREDIT_AMOUNT)
    )
FROM CONFORMED.FACT_GL_LINE
WHERE TRANSACTION_TYPE = 'JOURNAL'
  AND POSTING_FLAG = TRUE
GROUP BY TRANSACTION_ID
HAVING ABS(SUM(DEBIT_AMOUNT) - SUM(CREDIT_AMOUNT)) > 0.01;

-- Missing account references.
INSERT INTO CONTROL.RECON_EXCEPTION (
    RUN_ID, CHECK_NAME, ENTITY_TYPE, ENTITY_KEY,
    EXPECTED_VALUE, ACTUAL_VALUE, DIFFERENCE_VALUE, DETAILS
)
SELECT
    :RUN_ID,
    'MISSING_ACCOUNT_REFERENCE',
    'TRANSACTION_LINE',
    F.TRANSACTION_ID || ':' || F.LINE_ID,
    NULL,
    NULL,
    NULL,
    OBJECT_CONSTRUCT('account_id', F.ACCOUNT_ID)
FROM CONFORMED.FACT_GL_LINE F
LEFT JOIN CONFORMED.DIM_ACCOUNT A
  ON F.ACCOUNT_ID = A.ACCOUNT_ID
WHERE A.ACCOUNT_ID IS NULL;
